---
author: "Kowshik Raj"
output: html_document: 
theme: readable
toc: yes
editor_options: 
  chunk_output_type: inline
chunk_output_type: inline
---
  
```{r loadpackages, include = FALSE}
library(tidyverse)
library(e1071)
library(ggplot2)
library(caret)
library(rmarkdown)
library(corrplot)
library(psych)
library(rpart)
library(rpart.plot)
library(kernlab)
library(pROC)
library(randomForest)
library(ggpubr)
library(PRROC)
options("scipen"=100, "digits"=4)
```

```{r importdata}
client_data.df <- read.csv("UCI_Credit_Card.csv")
client_data.df <- client_data.df[-1]
```

_Data cleaning and Exploration:_
```{r}
## Categorical variable cleaning
#Cleaning SEX variable
table(client_data.df$s)
ggplot(client_data.df, aes(SEX)) + geom_bar() #Looks good

#Cleaning EDUCATION variable
table(client_data.df$EDUCATION) #Values 0,5,6 are present and they are undocumented
client_data.df$EDUCATION[client_data.df$EDUCATION %in% c(0,5,6)] <- 4 #Assigning 0,5,6 as 4
ggplot(client_data.df, aes(EDUCATION)) + geom_bar()

#Cleaning MARRIAGE variable
table(client_data.df$MARRIAGE)  #Undocumented value 0 present
client_data.df$MARRIAGE[client_data.df$MARRIAGE == 0] <- 3
ggplot(client_data.df, aes(MARRIAGE)) + geom_bar()

#Cleaning PAY_X variables
names(client_data.df)[6] <- "PAY_1" #Renaming PAY_0 to PAY_1
paylabels <- c("PAY_1","PAY_2","PAY_3","PAY_4","PAY_5","PAY_6")
for (p in paylabels) {
  client_data.df[client_data.df[,p] %in% c(-2,-1),p] <- 0
}
p1 <- ggplot(client_data.df, aes(PAY_1)) + geom_bar()
p2 <- ggplot(client_data.df, aes(PAY_2)) + geom_bar()
p3 <- ggplot(client_data.df, aes(PAY_3)) + geom_bar()
p4 <- ggplot(client_data.df, aes(PAY_4)) + geom_bar()
p5 <- ggplot(client_data.df, aes(PAY_5)) + geom_bar()
p6 <- ggplot(client_data.df, aes(PAY_6)) + geom_bar()
ggarrange(p1,p2,p3,p4,p5,p6)

#Making them factors
catLabels <- c("SEX", "EDUCATION", "MARRIAGE", "default.payment.next.month", paylabels)
client_data.df[catLabels] <- lapply(client_data.df[catLabels], as.factor)

## Numerical variables cleaning
#LIMIT_BAL variable
boxplot(client_data.df$LIMIT_BAL, main = "Boxplot of LIMIT_BAL variable", col = "RED") #Looks good
ggplot(client_data.df, aes(LIMIT_BAL)) + geom_histogram()

#AGE variable
hist(client_data.df$AGE, breaks = 12, col = "gray", main = "Histogram of Age", ylim = c(0,8000), labels = TRUE, xlab = "Age")
hist(client_data.df$AGE[client_data.df$default.payment.next.month == 1], breaks = 12, col = "gray", main = "Age-wise payment default chart", ylim = c(0,1500), labels = TRUE, xlab = "Age") #Looks good

#BILL_AMTX variables
billLabels <- c("BILL_AMT1","BILL_AMT2","BILL_AMT3","BILL_AMT4","BILL_AMT5","BILL_AMT6")
summary(client_data.df[billLabels]) #Looks good

#PAY_AMTX variables
amtLabels <- c("PAY_AMT1","PAY_AMT2","PAY_AMT3","PAY_AMT4","PAY_AMT5","PAY_AMT6")
summary(client_data.df[amtLabels]) #Looks good

summary(client_data.df[c("LIMIT_BAL","AGE", billLabels, amtLabels)])
sum(is.na(client_data.df[c("LIMIT_BAL","AGE", billLabels, amtLabels)]))
```

_Correlation plots and distribution wrt output variable:_
```{r Correlation plots}
# SEX, EDUCATION, MARRIAGE, AGE, LIMIT_BAL vs default.next.payment.month 
ggplot(client_data.df, aes(x=client_data.df$SEX, fill = default.payment.next.month)) + geom_bar() +
  xlab("Sex") + theme_bw() + ggtitle("Distribution of defaults across SEX") #Looks balanced; Female gender has more defaults

ggplot(client_data.df, aes(x=client_data.df$EDUCATION, fill = default.payment.next.month)) + geom_bar() +
  xlab("Education") + theme_bw() + ggtitle("Distribution of defaults across EDUCATION") #Looks balanced; University education has more defaults

ggplot(client_data.df, aes(x=client_data.df$MARRIAGE, fill = default.payment.next.month)) + geom_bar() +
  xlab("Marriage") + theme_bw() + ggtitle("Distribution of defaults across MARRIAGE") #Looks balanced; Singles have more defaults

ggplot(client_data.df, aes(AGE, fill = default.payment.next.month)) + geom_bar() +
  xlab("Age") + theme_classic() + ggtitle("Distribution of defaults across AGE") #Looks balanced; Age group 25-35 have more defaults

ggplot(client_data.df, aes(x=client_data.df$LIMIT_BAL, fill = default.payment.next.month)) + geom_histogram(binwidth = 1000) +
  stat_bin(bins = 30) + xlab("Credit Limit") + theme_classic() + ggtitle("Distribution of defaults across LIMIT_BAL") #Looks balanced

# Correlation among Numerical variables
corrplot(cor(client_data.df[billLabels]), method = "color", type = "upper",
         addCoef.col = "black",number.cex = 0.75) #Correlation among variables high; Expected because monthly bills are more or less same for a specific customer
corrplot(cor(client_data.df[amtLabels]), method = "color", type = "upper",
         addCoef.col = "black", number.cex = 0.75) #No Correlations exist
```

## Decision Tree implementation
```{r decisiontreemodel}
set.seed(40)
train1.index <- sample(c(1:nrow(client_data.df)), nrow(client_data.df)*0.7)
train1.df <- client_data.df[train1.index, ]
valid1.df <- client_data.df[-train1.index, ]
train.ct <- rpart(default.payment.next.month ~ ., data = train1.df, method = "class", cp = 0.001, maxdepth = 4)
prp(train.ct, type = 1, extra = 1, under = TRUE)

train.ct.pred <- predict(train.ct, train1.df, type = "class")
confusionMatrix(train.ct.pred, as.factor(train1.df$default.payment.next.month))

valid.ct.pred <- predict(train.ct, valid1.df, type = "class")
confusionMatrix(valid.ct.pred, as.factor(valid1.df$default.payment.next.month))
#accuracy - 0.822, roc - 0.691 
valid1.roc <- predict(train.ct, valid1.df, type = "prob")
roc.dt <- roc(valid1.df$default.payment.next.month, valid1.roc[,2])
plot.roc(roc.dt)
auc(roc.dt)
```

## Random Forest Implementation
```{r randomforestmodel}
set.seed(45)
train.rf.index <- sample(c(1:nrow(client_data.df)), nrow(client_data.df)*0.7)
train.rf <- client_data.df[train.rf.index, ]
test.rf <- client_data.df[-train.rf.index, ]
train.rf.out <- randomForest(default.payment.next.month ~ ., data = train.rf, importance = TRUE)
train.rf.out
importance(train.rf.out)
varImpPlot(train.rf.out)

train.rf.pred <- predict(train.rf.out, train.rf, type = "class")
confusionMatrix(train.rf.pred, train.rf$default.payment.next.month)

test.rf.pred <- predict(train.rf.out, test.rf, type = "class")
confusionMatrix(test.rf.pred, test.rf$default.payment.next.month)
#accuracy = 0.816, auc - 0.764
test.roc <- predict(train.rf.out, test.rf, type = "prob")
roc.rf <- roc(test.rf$default.payment.next.month, test.roc[,2])
plot.roc(roc.rf)
auc(roc.rf)
```


## Logistic Regression Implementation
```{r logitmodel}
set.seed(50)
train2.index <- sample(c(1:nrow(client_data.df)), nrow(client_data.df)*0.7)
train2.df <- client_data.df[train2.index, ]
valid2.df <- client_data.df[-train2.index, ]

logit.reg <- glm(default.payment.next.month ~ .,data = train2.df, family = "binomial")
summary(logit.reg)

logit.reg.pred.train <- predict(logit.reg, train2.df)
confusionMatrix(as.factor(ifelse(logit.reg.pred.train > 0.5, 1, 0)), as.factor(train2.df$default.payment.next.month))

logit.reg.pred.valid <- predict(logit.reg, valid2.df)
confusionMatrix(as.factor(ifelse(logit.reg.pred.valid > 0.5, 1, 0)), as.factor(valid2.df$default.payment.next.month))

#accuracy - 0.817, roc - 0.769
roc.logit <- roc(valid2.df$default.payment.next.month, logit.reg.pred.valid)
plot.roc(roc.logit)
auc(roc.logit)
```

## SVM Implementation
```{r SVMmodel}
set.seed(60)
train.index <- createDataPartition(client_data.df$default.payment.next.month, p=0.7, list= FALSE)
svm_train.df <- client_data.df[train.index, ]
svm_test.df <- client_data.df[-train.index, ]

svm1 <- svm(default.payment.next.month~ LIMIT_BAL+SEX+EDUCATION+MARRIAGE+AGE+PAY_1+PAY_2+PAY_3+PAY_4+PAY_5, data=svm_train.df, kernel = "radial")
summary(svm1)

#accuracy - 0 .82, auc - 0.5621
pred.svm <- predict(svm1, svm_test.df)
confusionMatrix(table(pred1, svm_test.df$default.payment.next.month))

pred.roc <- predict(svm1, svm_test.df)
roc.curve(svm_test.df$default.payment.next.month, pred.roc)
plot(roc.curve(svm_test.df$default.payment.next.month, pred.roc, curve = TRUE))
```

